import { API_HOST } from "@/global";
const API_URL: string = `${API_HOST}/api/v1`;
export const LOGIN_ENDPOINT: string = `${API_URL}/core/login/`;
export const SERVICE_TYPE_LIST_ENDPOINT = `${API_URL}/core/service-types/`;
export const TOKEN_VALIDATION_ENDPOINT = `${API_URL}/core/token-validation/`;
export const SERVICE_ENDPOINT = `${API_URL}/core/services/`;
export const SOFT_DELETE_ENDPOINT = `${API_URL}/core/generic-soft-delete/`;
export const PACKAGE_VALIDITY_ENDPOINT = `${API_URL}/core/package-validity-list/`;
export const PACKAGE_ENDPOINT: string = `${API_URL}/core/packages/`;
export const STATUS_CHANGE_ENDPOINT: string = `${API_URL}/core/generic-status-change/`;
export const STAFF_USER_ENDPOINT: string = `${API_URL}/core/staff-users/`;
export const ROLE_ENDPOINT: string = `${API_URL}/core/roles/`;
export const COUNTRY_ENDPOINT: string = `${API_URL}/engine/countries/`;